name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: oracle-actions/setup-java@v1
    - name: Set up JDK 23
      uses: oracle-actions/setup-java@v1
        with:
          website: oracle.com
          release: 23
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
